package de.patientenportal.entities;
// Generated 15.05.2017 03:00:21 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.CascadeType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "User", catalog = "patientenportal")
public class User implements java.io.Serializable {

	@GeneratedValue
	private int user_id;
	private String username;
	private String password;
	private String email;
	private String lastname;
	private String firstname;
	//private	Doctor doctor;
	
	public User() {
	}

	public User(int userId) {
		this.user_id = userId;
	}

	/*public User(int userId, String username, String password, String email, String lastname, String firstname, Doctor doctor) {
		this.user_id = userId;
		this.username = username;
		this.password = password;
		this.email = email;
		this.lastname = lastname;
		this.firstname = firstname;
		this.doctor = doctor;
	}*/
	
	/*@OneToOne
	public Doctor getDoctor() {
		return doctor;
	}

	public void setDoctor(Doctor doctor) {
		this.doctor = doctor;
	}
*/
	@Id
	@Column(name = "USER_ID", unique = true, nullable = false)
	public int getUserId() {
		return this.user_id;
	}

	public void setUserId(int userId) {
		this.user_id = userId;
	}

	@Column(name = "USERNAME", length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "EMAIL", length = 60)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "LASTNAME", length = 45)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "FIRSTNAME", length = 45)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

}
